name: Portfolio CI/CD

permissions:
  contents: read
  issues: write
  actions: read

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'
  AZURE_WEBAPP_NAME: 'curios4tech-portfolio'
  AZURE_RESOURCE_GROUP: 'Azure-RG'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        
      - name: Build application
        run: npm run build
        env:
          CI: true
          NODE_ENV: production

      - name: List build output
        run: |
          echo "Listing build output files:"
          ls -la
          echo "Listing .next directory:"
          ls -la .next || echo ".next directory not found"

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Check Azure Web App Status
        run: |
          echo "Checking Web App status..."
          az webapp show \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --query "{State:state,UserId:possibleOutboundIpAddresses}" -o json

      - name: Stop Azure Web App
        run: |
          echo "Stopping Web App..."
          az webapp stop --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }}
          sleep 10

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        id: deploy
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: .
          clean: true

      - name: Start Azure Web App
        if: always()
        run: |
          echo "Starting Web App..."
          az webapp start --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }}
          sleep 10  # Give it time to start up

      - name: Check Deployment Logs
        if: always()
        run: |
          echo "Fetching deployment logs..."
          az webapp log deployment show \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }}
          
          echo "Fetching recent web app logs..."
          az webapp log show \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --lines 100

      - name: Azure Logout
        if: always()
        run: az logout

      - name: Update deployment status
        if: always()
        run: |
          echo "Deployment Status: ${{ job.status }}"
          echo "Completed at: $(date -u)"
          echo "Workflow run: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
